design/design/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve


urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('main.urls', namespace='default')),
   path('main/', include('main.urls')),
   path('', RedirectView.as_view(url='/main/', permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




design/main/urls.py
from django.urls import path

from .views import CreateAppliView, AppliListView, DeleteAppliView
from .views import index
from .views import BBLoginView
from .views import RegisterDoneView, RegisterUserView
from .views import user_activate
from .views import profile
from .views import BBLogoutView

app_name = 'main'


urlpatterns = [
   path('', index, name='index'),
   path('accounts/login', BBLoginView.as_view(), name='login'),
   path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
   path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
   path('accounts/register/', RegisterUserView.as_view(), name='register'),
   path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
   path('accounts/profile/', profile, name='profile'),
   path('accounts/create/', CreateAppliView.as_view(), name='create_appli'),
   path('applications/', AppliListView.as_view(), name='appli_list'),
   path('applications/delete/<int:pk>/', DeleteAppliView.as_view(), name='appli_delete')
]

design/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator, FileExtensionValidator



class AdvUser(AbstractUser):

    login_validator = RegexValidator(
        regex=r"^[a-zA-Z-]+$",
        message="Введите допустимое слово. Должно содержать латиницу и дефисы."
    )

    fio_validator = RegexValidator(
        regex=r"^[а-яА-Я-]+\s[а-яА-Я-]+\s[а-яА-Я-]+$",
        message="Введите допустимое слово. Должно содержать кириллицу, пробелы и дефисы"
    )

    username = models.CharField(
        verbose_name="Логин",
        max_length=150,
        unique=True,
        blank=False,
        help_text=(
            "Разрешается использовать только латиницу и дефис."
        ),
        validators=[login_validator],
        error_messages={
            "unique": "Пользователь с таким именем уже существует.",
        },
    )
    first_name = models.CharField(verbose_name="ФИО", max_length=150, blank=False, validators=[fio_validator], help_text=(
            "Разрешается использовать только кириллицу, пробелы и дефис."))
    email = models.EmailField(verbose_name="Почта", blank=False)

class Category(models.Model):
    name = models.CharField(verbose_name="Категория", max_length=150, blank=False)

    def __str__(self):
        return self.name



class Appli(models.Model):
    name = models.CharField(verbose_name="Название", max_length=150, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    desc = models.CharField(verbose_name="Описание", max_length=150, blank=False)
    cat = models.ForeignKey("Category", verbose_name="Категория", max_length=150, blank=False, on_delete=models.CASCADE)
    image_app = models.ImageField(verbose_name="Фотография", upload_to='images/', blank=False, validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])])
    user = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name="Пользователь")

    STATUS_CHOICES = (
        ('Н', 'Новая'),
        ('П', 'Принята в работу'),
        ('В', 'Выполнено'),
    )

    stas = models.CharField(verbose_name="Статус заявки", max_length=1, choices=STATUS_CHOICES, blank=False,
                                  default='Н')

    image_admin = models.ImageField(verbose_name="Фотография дизайна", upload_to='images_admin/', validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])],
                                    help_text="Указать фото дизайна при смене статуса на 'Выполнено'", blank=True)

    comment_admin = models.TextField(verbose_name="Комментарий", help_text="Указать комментарий при смене статуса на 'Принята в работу'", blank=True)

    def __str__(self):
        return f"{self.name}, {self.cat}"

design/main/forms.py
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django import forms
from .models import AdvUser, Appli








class RegisterUserForm(forms.ModelForm):

   email = forms.EmailField(required=True,
                            label='Адрес электронной почты')
   password1 = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput,
                               help_text=password_validation.password_validators_help_text_html())
   password2 = forms.CharField(label='Пароль (повторно)',
                               widget=forms.PasswordInput,
                               help_text='Повторите тот же самый пароль еще раз')
   agree_to_processing = forms.BooleanField(required=True,
                                            widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))


   def clean_password1(self):
       password1 = self.cleaned_data['password1']
       if password1:
           password_validation.validate_password(password1)
       return password1


#проверка на совпадения двух паролей
   def clean(self):
       super().clean()
       password1 = self.cleaned_data['password1']
       password2 = self.cleaned_data['password2']
       if password1 and password2 and password1 != password2:
           errors = {'password2': ValidationError(
               'Введенные пароли не совпадают', code='password_mismatch'
           )}
           raise ValidationError(errors)


   def save(self, commit=True):
       user = super().save(commit=False)
       user.set_password(self.cleaned_data['password1'])
       user.is_active = True
       user.is_activated = True
       if commit:
           user.save()
       return user


   class Meta:
       model = AdvUser
       fields = ('first_name', 'username', 'email', 'password1', 'password2', 'agree_to_processing')

class CreateAppliForm(forms.ModelForm):

    def clean(self):
        image = self.cleaned_data.get('image_app')

        if image.size > 2097152:
            raise ValidationError("Прикрепляемая фотография должна быть меньше чем 2МБ")

    class Meta:
        model = Appli
        fields = ('name', 'desc', 'cat', 'image_app')

class CheckAppliForm(forms.ModelForm):

    def clean(self):
        stas = self.cleaned_data.get('stas')
        image = self.cleaned_data.get('image_admin')
        comment = self.cleaned_data.get('comment_admin')

        if self.instance.stas != 'Н':
            raise ValidationError("Статус можно менять только у новых заявок!")

        if stas == 'В' and not image:
            raise ValidationError("Заявке со статусом 'Выполнено' надо прикреплять фотографию дизайна!")

        if stas == 'П' and not comment:
            raise ValidationError("Заявке со статусом 'Принята в работу' надо оставлять комментарий!")

design/main/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.views import generic
from django.views.generic import TemplateView, DeleteView
from .forms import RegisterUserForm, CreateAppliForm
from django.core.signing import BadSignature
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LogoutView
from .models import AdvUser, Appli
from django.views.generic import CreateView



def index(request):
    num_applications = Appli.objects.filter(stas__exact='П').count()
    num_complete = Appli.objects.filter(stas__exact='В').order_by('-date')[:4]
    context = {
        'num_applications': num_applications,
        'num_complete': num_complete
    }
    return render(request, 'main/index.html', context)




class BBLoginView(LoginView):
   template_name = 'main/login.html'




class RegisterUserView(CreateView):
   model = AdvUser
   template_name = 'main/register_user.html'
   form_class = RegisterUserForm
   success_url = reverse_lazy('main:register_done')



class RegisterDoneView(TemplateView):
   template_name = 'main/register_done.html'



def user_activate(request, sign):
   try:
       username = signer.unsign(sign)
   except BadSignature:
       return render(request, 'main/bad_signature.html')
   user = get_object_or_404(AdvUser, username=username)
   if user.is_activated:
       template = 'main/user_is_activated.html'
   else:
       template = 'main/activation_done.html'
       user.is_activated = True
       user.is_active = True
       user.save()
   return render(request, template)




@login_required
def profile(request):
   return render(request, 'main/profile.html')

class BBLogoutView(LoginRequiredMixin, LogoutView):
   template_name = 'main/logout.html'

@login_required()
def UserProfile(request):
    status_filter = request.GET.get('status_filter', 'all')

    if status_filter == 'all':
        application_list = Appli.objects.filter(user=request.user).order_by('-date')
    else:
        application_list = Appli.objects.filter(user=request.user, stas=status_filter).order_by('-date')

    context = {
        'application_list': application_list,
        'status_filter': status_filter,
    }

    return render(request, 'main/appli_list.html', context)
class CreateAppliView(CreateView):
    form_class = CreateAppliForm
    template_name = 'main/create_appli.html'
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateAppliView, self).form_valid(form)

class AppliListView(generic.ListView):
    model = Appli
    context_object_name = 'application_list'
    template_name = 'application_list.html'

class DeleteAppliView(LoginRequiredMixin, DeleteView):
   model = Appli
   template_name = 'main/appli_delete.html'
   success_url = reverse_lazy('main:index')








design/main/templates/main/activation_done.html
{% extends "layout/basic.html" %}


{% block title %} Активация выполнена {% endblock %}


{% block content %}
<h2>Активация</h2>
<p>Активация пользователя завершена</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

design/main/templates/main/appli_delete.html
{% extends "layout/basic.html" %}


{% load bootstrap4 %}


{% block title %} Удаление Заявки {% endblock %}


{% block content %}
<h2>Удаление заявки {{ app.name }}</h2>
 {% if object.stas == 'Н' %}
   <p>Вы уверены, что хотите удалить эту заявку?</p>
      <form method="post">
         {% csrf_token %}
         {% buttons submit='Удалить' %} {% endbuttons %}
      </form>
      {% else %}
             <p>Можно удалять только заявки со статусом "Новая"</p>
      {% endif %}
{% endblock %}


design/main/templates/main/appli_list.html
{% extends "layout/basic.html" %}

{% block content %}
    <h1>Мои заявки</h1>
    <hr>

    {% if application_list %}
<label for="status_filter">Фильтр по статусу:</label>
        <select name="status_filter" id="status_filter" onchange="location.href = '{% url 'main:appli_list' %}?stas=' + this.value;">
            <option value="all" {% if status_filter == 'all' %}selected{% endif %}>Все</option>
            <option value="Н" {% if status_filter == 'Н' %}selected{% endif %}>Новые</option>
            <option value="П" {% if status_filter == 'П' %}selected{% endif %}>В работе</option>
            <option value="В" {% if status_filter == 'В' %}selected{% endif %}>Выполненные</option>
        </select>
    <ul>

      {% for app in application_list %}
      <li>
            <p><strong>Дата создания:</strong> {{app.date}}</p>
            <p><strong>Название:</strong> {{app.name}}</p>
            <p><strong>Описание:</strong> {{app.desc}}</p>
            <p><strong>Категория:</strong> {{app.cat}}</p>
            <p><strong>Статус заявки:</strong> {{app.stas}}</p>
            <nav class="col-md-auto nav flex-column">
                <a class="nav-link root" href="{% url 'main:appli_delete' pk=app.id %}">Удалить</a>
            </nav>
            <hr>

      </li>
      {% endfor %}
    </ul>
    {% else %}
    <label for="status_filter">Фильтр по статусу:</label>
        <select name="status_filter" id="status_filter" onchange="location.href = '{% url 'main:appli_list' %}?stas=' + this.value;">
            <option value="all" {% if status_filter == 'all' %}selected{% endif %}>Все</option>
            <option value="Н" {% if status_filter == 'Н' %}selected{% endif %}>Новые</option>
            <option value="П" {% if status_filter == 'П' %}selected{% endif %}>В работе</option>
            <option value="В" {% if status_filter == 'В' %}selected{% endif %}>Выполненные</option>
        </select>
<h2> у вас нету заявок</h2>
{% endif %}
{% endblock %}

design/main/templates/main/bad_signature.html
{% extends "layout/basic.html" %}


{% block title %} Ошибка при активации {% endblock %}


{% block content %}
<h2>Активация</h2>
<p>Регистрация пользователя прошла неудачно.</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

design/main/templates/main/create_appli.html
{% extends "layout/basic.html" %}

{% block content %}
<h2>Создание заявки</h2>
{% if user.is_authenticated %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Создать">
</form>
{% endif %}
{% endblock %}

design/main/templates/main/index.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block content %}

    {% if user.is_authenticated %}
   <h4>Добро пожаловать! {{user.first_name}}</h4>
    {% if num_complete %}
    <p>Список последних выполненных заявок:</p>
    <ul style="list-style: none">
    {% for app in num_complete %}
        <li><strong>Дата:</strong> {{app.date}}</li>
        <li><strong>Название:</strong> {{app.name}}</li>
        <li><strong>Категория:</strong> {{app.cat}}</li>
        <li><img style="width: 160px; height: 150px" class="img" src="/media/{{ app.image_app }}"></li>
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </ul>
    {% else %}
     <p>На данный момент выполненных заявок нет</p>
    {% endif %}
    <p>Количество заявок находящихся в работе: {{ num_applications }}</p>
    {% else %}
    <h3>Добро пожаловать!</h3>
    <p>Список последних выполненных заявок:</p>
    <ul style="list-style: none;">
    {% for app in num_complete %}
        <li><strong >Дата:</strong> {{app.date}}</li>
        <li><strong>Название:</strong> {{app.name}}</li>
        <li><strong>Категория:</strong> {{app.cat}}</li>
        <li><img style="width: 100px; height: 100px" class="img" src="/media/{{ app.image_app }}"></li>
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}

design/main/templates/main/login.html
{% extends "layout/basic.html" %}


{% load bootstrap4 %}


{% block title %} Вход {% endblock %}


{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
   {% csrf_token %}
   {% bootstrap_form form layout='horizontal' %}
   <input type="hidden" name="next" value="{{ next }}">
   {% buttons submit='Войти' %} {% endbuttons %}
</form>
{% endif %}
{% endblock %}

design/main/templates/main/logout.html
{% extends "layout/basic.html" %}


{% block title %} Выход {% endblock %}


{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

design/main/templates/main/profile.html
{% extends "layout/basic.html" %}


{% load bootstrap4 %}


{% block title %} Профиль пользователя {% endblock %}


{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<h2>Ваши заявки:</h2>
  <ul>
  {% for app in applications %}
        <li><strong >Дата:</strong> {{app.date}}</li>
        <li><strong>Название:</strong> {{app.name}}</li>
        <li><strong>Категория:</strong> {{app.cat}}</li>
        <li><img style="width: 100px; height: 100px" class="img" src="/media/{{ app.image_app }}"></li>
        {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  </ul>
{% else %}
<h2>У вас пока нет заявок.</h2>
{% endif %}

{% endblock %}

design/main/templates/main/register_done.html
{% extends "layout/basic.html" %}


{% block title %} Регистрация завершена {% endblock %}


{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена</p>
{% endblock %}

design/main/templates/main/register_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% block title %} Регистрация {% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
{% csrf_token %}
{% bootstrap_form form layout='horizontal' %}
{% buttons submit='Зарегистрироваться' %} {% endbuttons %}
</form>
{% endblock %}

design/main/templates/main/user_is_activated.html
{% extends "layout/basic.html" %}


{% block title %} Пользователь уже активирован {% endblock %}


{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем уже был активирован ранее.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}